required:
  - warehouseId
  - quantity
  - productId
  - productInsertId
properties:
  id:
    description: The unique identifier for the product insert
    type: integer
  quantity:
    description: The quantity of products associated with the SKU
    type: integer
  productId:
    type: integer
  productInsertId:
    type: integer
  inventoryId:
    type: integer
  inventory:
    $ref: '#/definitions/Inventory'
  warehouseId:
    description: The unique identifier for the warehouse this insert is located in
    type: integer
type: object
