properties:
  id:
    description: ID for the product
    type: integer
  name:
    description: Name of this product
    type: string
  description:
    description: Description of this product
    type: string
  internalSku:
    description: SKU used internally at FDC to identify this product
    type: string
  type:
    type: integer
  quantity:
    description: The quantity of physical items in this product
    type: integer
  isActive:
    description: Is this product active in the system?
    type: boolean
  isCharged:
    description: Has this item been paid for?
    type: boolean
  defaultValue:
    description: Default declared value for a product
    type: number
    format: float
  skuProducts:
    description: The SKUs for this product
    type: array
    items:
      $ref: '#/definitions/SkuProduct'
  merchant:
    $ref: '#/definitions/Merchant'
  inventory:
    description: Inventory for this product
    type: array
    items:
      $ref: '#/definitions/Inventory'
  productInserts:
    type: array
    items:
      $ref: '#/definitions/ProductInsert'
type: object
