swagger: '2.0'
info:
  title: Api Next
  description: Documentation for FDC's API
  termsOfService: 'https://fulfillment.github.io/api/terms/'
  contact:
    email: dev@fulfillment.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: '2.0'
basePath: /v2
parameters:
  authHeader:
    name: Authorization
    in: header
    description: OAuth 2.0 Bearer Access token required to authenticate the request
    required: true
    type: string
