post:
  tags:
    - Product
  summary: Create a new sku association for this product
  description: >-
    If you pass an existing SKU -- IE a SKU with an existing ID -- a
    relationship between the existing SKU and this product will be created. <br>
    If no ID is supplied (or the ID is 0) a new SKU will be created.
  operationId: createSkuProduct
  parameters:
    - $ref: '#/parameters/authHeader'
    - name: id
      in: path
      description: Product ID
      required: true
      type: integer
      format: int64
    - name: body
      in: body
      description: The insert(s) to create
      required: true
      schema:
        type: array
        items:
          $ref: '#/definitions/SkuProduct'
  responses:
    '200':
      description: success
      schema:
        type: array
        items:
          $ref: '#/definitions/SkuProduct'
    '400':
      description: Invalid sku object
    '403':
      description: Insufficient permissions to create skus for this product
