get:
  tags:
    - Product
  summary: Get overview of product jobs
  operationId: getProductJobs
  parameters:
    - $ref: '#/parameters/authHeader'
  responses:
    '200':
      description: success
      schema:
        type: array
        items:
          $ref: '#/definitions/Job'
