get:
  tags:
    - Product
  summary: Get the inserts available for this product
  description: ''
  parameters:
    - $ref: '#/parameters/authHeader'
    - name: id
      in: path
      description: ID of product
      required: true
      type: integer
      format: int64
  responses:
    '200':
      description: success
      schema:
        type: array
        items:
          $ref: '#/definitions/ProductInsert'
    '400':
      description: Invalid ID supplied
    '404':
      description: Product not found
post:
  tags:
    - Product
  summary: Create a new insert association for this product
  description: >-
    If you pass an existing insert -- IE an insert with an existing ID -- a
    relationship between the existing insert and this product will be created.
    /\n /\n If no ID is supplied (or the ID is 0) a new insert will be created.
  operationId: createProductInserts
  parameters:
    - $ref: '#/parameters/authHeader'
    - name: id
      in: path
      description: Id of the product
      required: true
      type: integer
    - name: body
      in: body
      description: The insert(s) to create
      required: true
      schema:
        type: array
        items:
          $ref: '#/definitions/ProductInsert'
  responses:
    '200':
      description: success
      schema:
        type: array
        items:
          $ref: '#/definitions/ProductInsert'
    '400':
      description: Invalid insert object
    '403':
      description: Insufficient permissions to create inserts for this product
