delete:
  tags:
    - Product
  summary: Removes a product insert association
  description: >-
    Unless explicitly stated with the <b>deleteInsert</b> param <b>only the
    association between the insert and the product will be removed.</b>
  parameters:
    - $ref: '#/parameters/authHeader'
    - name: id
      in: path
      description: Id of the product
      required: true
      type: integer
    - name: insertId
      in: path
      description: Id of the insert relationship to delete
      required: true
      type: integer
    - name: deleteInsert
      in: query
      description: Indicate whether the insert should be deleted.
      required: false
      type: boolean
  responses:
    '403':
      description: Insufficient privileges to access this insert relationship
    '404':
      description: Insert relationship not found
