post:
  tags:
    - Product
  summary: Batch upload products from CSV or XML
  description: |-
    This request must be made as <strong>form-data</strong>. </br>
         *             Accepted formats are <strong>csv</strong> and <strong>xml</strong>
  operationId: batchUploadProducts
  parameters:
    - $ref: '#/parameters/authHeader'
    - name: file
      in: formData
      description: The file containing products
      required: true
      type: file
  responses:
    '200':
      description: success
